### ISSUE TITLE
WiFi Access point Mode

### ISSUE THREAD

**Issue by iamnarendrans** [nopnop2002/esp-idf-ftpClient#13]
Is it possible to do FTP in WiFi Access point configuration?

I've tried that, I'm getting something like PASV configuration error.

**Comment by nopnop2002** [comment]
>Is it possible to do FTP in WiFi Access point configuration?

what do you want to do?


There is no relationship between FTP's PASV/ACTIVE mode and WiFI's Station/AP mode.

This is common usage.

```
+------------+              +---------+              +------------+
| Ftp Client | --Connect--> |  Router | --Connect--> | Ftp Server |
+------------+              +---------+              +------------+
```


If the FTP server is running on WiFI AP (Hot Spot), this will work.
```
+------------+              +------------+
| Ftp Client | --Connect--> | Ftp Server |
| ST Mode    |              | Hot Spot   |
+------------+              +------------+
```


The following configurations are not supported.
This will require a lot of code changes.

```
+------------+              +------------+
| Ftp Client | --Connect--> | Ftp Server |
| AP Mode    |              |            |
+------------+              +------------+
```

**Comment by iamnarendrans** [comment]
@nopnop2002 

Thanks for your response, I've one more query

Is there any transfer speed rate vary for STA and AP modes?
Because, I'm feeling that AP mode has lower data transfer rate.

**Comment by nopnop2002** [comment]
>Is there any transfer speed rate vary for STA and AP modes?

The same question has been posted.

No answer yet.

https://www.esp32.com/viewtopic.php?t=42349

I think the speed of STA mode depends on your network environment, such as the performance of your WiFi router.

I'm using a cheap old WiFi router, and only part of the wired LAN is GigaBit.

The benchmarks when using STA mode should be different between my network environment and your network environment.

**Comment by iamnarendrans** [comment]
@nopnop2002 
Thanks for you reply.

**Comment by iamnarendrans** [comment]
@nopnop2002 
Thanks for your reply !
