### ISSUE TITLE
Pass file from arduino SD library

### ISSUE THREAD

**Issue by edouardreg** [nopnop2002/esp-idf-ftpClient#4]
Hello, thanks for this beautiful client !

Perhaps it's not an issue but more a new feature : I'm using arduino-esp32 as component in esp-idf V4.4, and use arduino SD library to write files on a SPI connected SD card.

The FS partion is mounted with SD.begin(SPI_CS_PIN)...from the arduino SD library but then I can't success in passing the file (/test.txt on the SD) to the FTP client function : ftpClient->ftpClientPut(srcFileName, dstFileName, FTP_CLIENT_TEXT, ftpClientNetBuf);

How can I use the file system created with arduino SD library with your client ?

Thanks by advance !

**Comment by nopnop2002** [comment]
You may be able to find a solution by examining the source of the arduino SD library.

But it's not easy.

It's a good idea to find an FTP client that you can use in your Arduino environment.

**Comment by edouardreg** [comment]
So I have succeeded : just need to use /sd/filename.xxx as srcFileName
Thanks for your work !
